### PR TITLE
Fixed several bugs in makeotf. It now works without a hitch in 2D and/or TIFF

### PR DESCRIPTION
**Pull request by linshaova**
As indicated in the subject line...

After this merge, would the anaconda installation be automatically updated to compile from the latest version? Thanks!

### CODE REVIEW

**Comment by tlambert03** [comment]
awesome thanks!

> would the anaconda installation be automatically updated to compile from the latest version?

nope, we need to cut a new "release" (easy to do).  The idea is that we can merge to master as much as we want, and then when we're ready to release a new version to anaconda:

1) [create a new release](https://github.com/scopetools/cudasirecon/releases) here in this github repo
2) Submit a PR to https://github.com/conda-forge/cudasirecon-feedstock that just does 2 things:
   - update the version on [this line](https://github.com/conda-forge/cudasirecon-feedstock/blob/master/recipe/meta.yaml#L2)
   - update the sha on [this line](https://github.com/conda-forge/cudasirecon-feedstock/blob/master/recipe/meta.yaml#L10) to the sha for the targ.gz from the corresponding github release. 

I can do it if you'd like.  Are you ready to release this?

**Comment by linshaova** [comment]
Yes please go ahead with the new release. Some collaborator wants to use this for their TIRF-SIM soon. Thanks!

**Comment by linshaova** [comment]
I peeked in the conda-forge/cudasirecon-feedstock PR. From what I could understand, you are waiting for a final conda-forge approval for updating the cudasirecon package. Is that right?

**Comment by tlambert03** [comment]
> From what I could understand, you are waiting for a final conda-forge approval for updating the cudasirecon package. Is that right?

nope, we control that feedstock (conda-forge admins only need to approve the original creation of the feedstock, after that it's up to us).  I just merged it.  I also added you as a feedstock maintainer in this PR too, I think you'll get an invite?

**Comment by linshaova** [comment]
Okay, the reason I asked is that half an hour ago I updated cudasirecon in my conda but it looked like "makeotf" is still the old version. How long normally does the conda server to refresh?
Also GitHub is kind of annoying because I kept trying to change my preferred email for communication and it never took effect for some reason. Not sure how to achieve that...

    On Wednesday, July 14, 2021, 5:07:52 PM EDT, Talley Lambert ***@***.***> wrote:  
 
 



From what I could understand, you are waiting for a final conda-forge approval for updating the cudasirecon package. Is that right?


nope, we control that feedstock (conda-forge admins only need to approve the original creation of the feedstock, after that it's up to us). I just merged it. I also added you as a feedstock maintainer in this PR too, I think you'll get an invite?

**Comment by tlambert03** [comment]
> Okay, the reason I asked is that half an hour ago I updated cudasirecon in my conda but it looked like "makeotf" is still the old version. How long normally does the conda server to refresh?

a _bit_ longer than that :)  First, I opened the PR at the feedstock... (then I left work and went home).  then, I checked to see if all of building and tests had passed... They had, so I merged it into master (about 17 minutes ago).  It's currently building in the master branch, you can watch it here: https://github.com/conda-forge/cudasirecon-feedstock/runs/3070923904

as they finish, they upload to conda cloud, which is where you can ultimately check the current versions (and OS) available: https://anaconda.org/conda-forge/cudasirecon

**Comment by tlambert03** [comment]
also @linshaova, rather than checking the functionality of the program, you should run `conda list cudasirecon` to show what version you have.  Note, we also should have updated the version string in `CMakeLists`...

**Comment by linshaova** [comment]
Good point. I did notice the version number 1.1.1 when I did an update later yesterday afternoon.


On Thursday, July 15, 2021, 8:20 AM, Talley Lambert ***@***.***> wrote:




also @linshaova, rather than checking the functionality of the program, you should run conda list cudasirecon to show what version you have. Note, we also should have updated the version string in CMakeLists...

**Pull request merged**
